Name: Yirou Qian
USC ID: 4354716429
Project Phase 1


All Compilation Steps on viterbi-scf2.usc.edu:

1. g++ -o admission Admission.cpp -lnsl -lresolv
2. g++ -o department Department.cpp -lnsl -lresolv



Executing Steps on terminal:

1. Admission.cpp (server): ./admission

2. Department.cpp (client): ./department